spring.application.name=newApp


server.port=7070


erpnext.url=http://erpnext.localhost:8000/

spring.mvc.view.prefix=/
spring.mvc.view.suffix=.jsp

spring.datasource.url=jdbc:mysql://erpnext.localhost:3306/_a7300fff2917cb8c
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver




